#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_ACQUJEWELWFS"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_ACQUJEWELWFS+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_ACQUJEWELWFS"
fi


# FPS name
fpsname="acquJewelWFS"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaoio.acquireJewelWFS"

# short description
fpsdescr="WFS acquire frames for Jewel/NRM data"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
    addfpscmd "setval ${fpsfname}.AOloopindex ${CACAO_LOOPNUMBER}"
    addfpscmd "setval ${fpsfname}.insname aol${CACAO_LOOPNUMBER}_wfsim"

    # addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1" # infinite loop
    # addfpscmd "setval ${fpsfname}.procinfo.triggermode 3" # semaphore
    # addfpscmd "setval ${fpsfname}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_wfsim"

	# addfpscmd "setval ${fpsfname}.comp.darksub ON"
    # addfpscmd "setval ${fpsfname}.comp.WFSnormalize ON"
    # addfpscmd "setval ${fpsfname}.comp.WFSrefsub ON"
    # addfpscmd "setval ${fpsfname}.comp.WFSsigav ON"
    # addfpscmd "setval ${fpsfname}.comp.WFSrefc ON"
    # addfpscmd "setval ${fpsfname}.comp.imtotal ON"
    # addfpscmd "setval ${fpsfname}.comp.normwfsim ON"

    # addfpscmd "setval ${fpsfname}.wfszpo aol${CACAO_LOOPNUMBER}_wfszpo"
}



source milk-fpslist-addentry
